bachapartybanking/urls.py
from bacha.views import CreateProductForm, ProductBuy, ProductDelete, ProductSearch, ProductView, ProductsView, editProductView
from bacha.views import registerPage, userProfile, justBase, transactionForm, TransactionView, TransactionsView, CreateJobForm, JobView, editJobView, editProfilePage, JobSearch, JobJoin, JobLeave, JobPay, JobsView
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

from bachapartybanking.bacha.views import depositForm, withdrawForm

urlpatterns = [
    # Auth
    path('admin/', admin.site.urls, name='admin'),
    path('signup/', registerPage, name='signup'),
    path('user/edit', editProfilePage, name='edit-profile'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/doc/', include('django.contrib.admindocs.urls')), 
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),

    # Homes
    path('home/', userProfile, name='home'),
    path('user/home/<str:notification>', userProfile, name='homeWithNotif'),
    path('', userProfile, name='Landing'),
    path('base/', justBase, name='base'),

    # Transactions
    path('view/transaction/<int:id>', TransactionView, name='transaction'),
    path('user/transaction', transactionForm, name='runTransaction'),
    path('user/transactions', TransactionsView, name="transactions"),

    # jobs
    path('user/job', CreateJobForm, name="create_job"),
    path('view/job/<int:id>', JobView, name='view_job'),
    path('join/job/<int:id>', JobJoin, name='join_job'),
    path('leave/job/<int:id>', JobLeave, name='leave_job'),
    path('pay/job/<int:id>', JobPay, name='pay_job'),
    path('user/jobs', JobsView, name='jobs'),
    path('search/job/', JobSearch, name='search_jobs'),
    path('view/job/edit/<int:id>', editJobView, name='job_edit'),

    # Products
    path('user/product', CreateProductForm, name="create_product"),
    path('view/product/<int:id>', ProductView, name='view_product'),
    path('delete/product/<int:id>', ProductDelete, name='delete_product'),
    path('buy/product/<int:id>', ProductBuy, name='buy_product'),
    path('user/products', ProductsView, name='products'),
    path('search/products/', ProductSearch, name='search_products'),
    path('edit/product/<int:id>', editProductView, name='product_edit'),

    # Favicon
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),name="favicon.ico"),

    # Deposit & Withdrawl
    path('user/deposit', depositForm, name='Deposit Money'),
    path('user/withdraw', withdrawForm, name='Withdraw Money'),
]

bacha/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError

def validate_positive(value):
    if value <= 0:
        raise ValidationError(
            _('%(value)s is not a positive number not equal to 0'),
            params={'value': value},
        )
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(blank=True, null=True)
    balance = models.SmallIntegerField(verbose_name='Bank Balance', default=10)

    username = models.CharField(max_length=100, blank=True, null=True)

    def __str__(self):
        return " ".join([self.first_name, self.last_name])

class Comment(models.Model):
    commenter = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="commenter")
    comment = models.TextField(verbose_name='Comment',max_length=2000)
    time = models.DateTimeField(auto_now_add=True, verbose_name='Comment Time')
    def __str__(self):
        return self.comment

class Review(models.Model):
    choices = [
        (1, "1 - Really Bad"),
        (2, "2 - Bad"),
        (3, "3 - Ok"),
        (4, "4 - Good"),
        (5, "5 - Really Good")
    ]
    stars = models.SmallIntegerField(verbose_name="Star Rating", choices=choices)
    commenter = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="reviewer")
    comment = models.TextField(verbose_name='Comment', max_length=2000)
    def __str__(self):
        return " ".join([str(self.stars), self.comment])

class Transaction(models.Model):
    payer = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="payer") # The Foreign key to the Profiles involved
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="receiver")

    description = models.TextField(verbose_name='Message to receiver',max_length=2000)
    amount = models.SmallIntegerField(verbose_name='Amount', validators=[validate_positive])

    time = models.DateTimeField(auto_now_add=True, verbose_name='Time of Transaction', blank=True)

    choices = (
        (True, 'Read'),
        (False, 'Unread')
    )
    read = models.BooleanField(default=False, verbose_name="Read By Receiver", choices=choices)
    
    def __str__(self):
        return self.description

class Product(models.Model):
    seller = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="seller") # The Foreign key to the Profiles involved
    buyers = models.ManyToManyField(Profile, related_name="buyers")

    transactions = models.ManyToManyField(Transaction)

    # Some of the Product's attributes
    name = models.CharField(verbose_name='Product Name', max_length=50)
    description = models.TextField(verbose_name='Product Description',max_length=2000)
    price = models.PositiveSmallIntegerField(verbose_name='Price')
    availability = models.SmallIntegerField(verbose_name="Amount of Products", validators=[validate_positive])
    reviews = models.ManyToManyField(Review)
    def __str__(self):
        return self.name

class Job(models.Model):
    employer = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="employer")

    name = models.CharField(verbose_name='Work Name', max_length=50)
    description = models.TextField(verbose_name='Work Description',max_length=2000)
    pay = models.PositiveSmallIntegerField(verbose_name='Pay')
    minutes = models.PositiveSmallIntegerField(verbose_name='Physical Minutes')
    BOOL_CHOICES = ((True, 'Public'), (False, 'Private'))
    availability = models.BooleanField(verbose_name="Job Avalability", choices=BOOL_CHOICES) # True if Public False if Private
    
    transactions = models.ManyToManyField(Transaction)

    workers = models.ManyToManyField(Profile)
    comments = models.ManyToManyField(Comment)

    def __str__(self):
        return self.name

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

  
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Bachaparty Banking{% endblock %}</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}"/>

{% comment %}   
    <!-- UIkit CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.7.0/dist/css/uikit.min.css" />

  <!-- UIkit JS -->
  <script src="https://cdn.jsdelivr.net/npm/uikit@3.7.0/dist/js/uikit.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/uikit@3.7.0/dist/js/uikit-icons.min.js"></script> {% endcomment %}

  {% block scripts %} {% endblock %}

  <style>
    body {
      margin: 0;
      font-family: Arial, Helvetica, sans-serif;
    }
    /* Add a black background color to the top navigation */
    nav, footer {
      background-color: #3c3744;
      overflow: hidden;
    }

    footer p {
      float: left;
      color: #f2f2f2;
      text-align: center;
    }
      
      /* Style the links inside the navigation bar */
    nav a, nav p {
        float: left;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
    }

    /* Change the color of links on hover */
    nav a:hover {
        background-color: #ddd;
        color: black;
    }

    /* Add a color to the active/current link */
    nav a.active {
        background-color: #62C370;
        color: white;
    }

    nav a.nav-right {
        float: right;
    }
  </style>
  <style>
    * {
      box-sizing: border-box;
    }
    
    /* Float four columns side by side */
    .small-column {
      float: left;
      width: 23%;
      padding: 0 10px;
    }
    
    .big-column {
      float: left;
      width: 50%;
      padding: 0 10px;
    }
    
    .huge-column {
      float: left;
      width: 73%;
      padding: 0 10px;
    }
    
    /* Remove extra left and right margins, due to padding */
    .row {margin: 0 -5px;}
    
    /* Clear floats after the columns */
    .row:after {
      content: "";
      display: table;
      clear: both;
    }
    
    /* Responsive columns */
    @media screen and (max-width: 600px) {
      .column {
        width: 100%;
        display: block;
        margin-bottom: 20px;
      }
    }
    
    /* Style the counter cards */
    .card {
      box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
      padding: 16px;
      text-align: center;
      background-color: #f1f1f1;
    }
    
    .button {
      background-color: white;
      color: black;
      padding: 5px;
      border: 2px solid #555555;
    }
    
    #transactions {
      font-family: Arial, Helvetica, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    #transactions td, #transactions th {
      border: 1px solid #ddd;
      padding: 8px;
    }
    
    #transactions tr:nth-child(even){background-color: #f2f2f2;}
    
    #transactions tr:hover {background-color: #ddd;}
    
    #transactions th {
      padding-top: 12px;
      padding-bottom: 12px;
      text-align: left;
      background-color: #04AA6D;
      color: white;
    }
    .form-group {
      padding: 2px;
      display: block;
    }
    </style>

 </head>

<body>

  <nav>
    <a href="{% url 'home' %}" class='active'> Home </a>
    <a><strong>Bachaparty Banking</strong></a>
    <a href="{% url 'transactions' %}"> Transactions </a>
    <a href="{% url 'jobs' %}"> Jobs </a>
    <a href="{% url 'products' %}"> Products </a>
    
        {% if user.is_authenticated %}
          {% comment %} <a class="nav-right" href="{% url 'admin/' %}"> Admin </a> {% endcomment %}
          <a class="nav-right" href="{% url 'logout' %}">Log Out</a>
          <a class="nav-right">Hello, {{ user.first_name|safe|capfirst }} {{ user.last_name|safe|capfirst }}</a>
        
        {% else %}
{% comment %}           <a class="nav-right" href="{% url 'admin/' %}"> Admin </a>
 {% endcomment %}          <a class="nav-right" href="{% url 'login' %}"> Login </a>
          <a class="nav-right" href="{% url 'signup' %}"> Sign Up </a>
          
        {% endif %}
     
  </nav>
  <main style="padding:10px">
    {% block content %}
    {% endblock %}
  </main>
</body>

<footer style="padding: 20px;">
<br>
<br>
  <img src="{% static 'favicon.png' %}" alt="Bachaparty logo" style="float: left;">
  <p style="float: right;">Bachaparty Banking</p>
  <br>
  <p style="float: right;">All Rights Reserved</p>
  <br>
  <p style="float: right;">Contact Bobo for any problems</p>

</footer>
</html>

templates/blank.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ text }}</h1>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% block title %}
Home
{% endblock title %}

{% block style %}
<style>
* {
  box-sizing: border-box;
}

/* Float four columns side by side */
.small-column {
  float: left;
  width: 23%;
  padding: 0 10px;
}

.big-column {
  float: left;
  width: 50%;
  padding: 0 10px;
}

.huge-column {
  float: left;
  width: 73%;
  padding: 0 10px;
}

/* Remove extra left and right margins, due to padding */
.row {margin: 0 -5px;}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive columns */
@media screen and (max-width: 600px) {
  .column {
    width: 100%;
    display: block;
    margin-bottom: 20px;
  }
}

/* Style the counter cards */
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  padding: 16px;
  text-align: center;
  background-color: #f1f1f1;
}

.button {
  background-color: white;
  color: black;
  padding: 5px;
  border: 2px solid #555555;
}

#transactions {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#transactions td, #transactions th {
  border: 1px solid #ddd;
  padding: 8px;
}

#transactions tr:nth-child(even){background-color: #f2f2f2;}

#transactions tr:hover {background-color: #ddd;}

#transactions th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #04AA6D;
  color: white;
}

</style>
{% endblock %}

{% block content %}
<br>

<div class="row">
  <div class="small-column">
    <div class="card">
        <h1 class="card-title">Balance</h1>
        <h1 id="balance" class="card-text">{{ balance }}</h1>
    </div>
  </div>
  <div class="small-column">
    <div class="card">
        <h2 class="card-title">Welcome, {{ full_name| safe | capfirst }}</h2>
        <h3 class="card-text">You have {{ num_transactions }} new notifications</h3>
    </div>
  </div>
  <div class="big-column">
    <div class="card">
        {% if len != 0 %}
        <table id="transactions">
            <tr>
                <th>Sender</th>
                <th>Receiver</th>
                <th>Amount</th>
                <th>Description</th>
                <th>Info</th>
            </tr>
            {% for transaction in transactions %}
            <tr>
                <td>{{ transaction.payer.first_name|safe|capfirst }} {{ transaction.payer.last_name|safe|capfirst }}</td>
                <td>{{ transaction.receiver.first_name|safe|capfirst }} {{ transaction.receiver.last_name|safe|capfirst }}</td>
                <td>${{ transaction.amount }}</td>
                <td> {{ transaction.description|safe }} </td>
                <td> <a href="{% url 'transaction' transaction.id %}">Info</a></td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        No Transactions
        <br>
        <br>
        {% endif %}
        <br>
        <a class="button" href="{% url 'runTransaction' %}">Create a Transaction</a>
        <a class="button" href="{% url 'transactions' %}">View all Transactions</a>
    </div>
  </div>
  
</div>

<script>
balance = document.getElementById('balance')
console.log(balance)
if (parseFloat(balance.textContent) < 10) {
    balance.style.color = 'red'
} else if (parseFloat(balance.textContent) < 50) {
    balance.style.color = 'orange'
} else if (parseFloat(balance.textContent) >= 50) {
    balance.style.color = 'green'
}
</script>
<br>
<div class="row">
  <div class="small-column">
    <div class="card">
        <h1 class="card-title">Information</h1>
        <p class="card-text"> Email: {{ email }}</p>
        <p class="card-text"> Username: {{ username }}</p>
        <p class="card-text"> Hello {{ first_name|safe|capfirst }} {{ last_name|safe|capfirst }}!</p>
        <br>
        <a class="button" href="{% url 'edit-profile' %}">Edit Profile</a>
    </div>
  </div>
  <div class="huge-column">
    <div class="card">
        {% if job_len != 0 %}
        <table id="transactions">
            <tr>
                <th>Name</th>
                <th>Employer</th>
                <th>Pay</th>
                <th>Minutes</th>
                <th>Availibility</th>
                <th>Workers</th>
                <th>Info</th>
                <th>Edit</th>
            </tr>
            {% for job in jobs %}
            <tr>
                <td>{{ job.name }}</td>
                <td>{{ job.employer.first_name|safe|capfirst }} {{ job.employer.last_name|safe|capfirst }}</td>
                <td>${{ job.pay }}</td>
                <td>{{ job.minutes }}</td>
                <td>{{ job.get_availability_display }}</td>
                <td>
                {% for person in job.workers.all %}
                  <p>{{ person.first_name|safe|capfirst }} {{ person.last_name|safe|capfirst }}</p>
                {% empty %}
                  <p class='card-text'>No Workers</p>
                {% endfor %}
      </td>
                <td> <a href="{% url 'view_job' job.id %}">Info</a></td>
                <td> <a href="{% url 'job_edit' job.id %}">Edit</a></td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        No Jobs
        <br>
        <br>
        {% endif %}
        <br>
        <a class="button" href="{% url 'create_job' %}">Create a Job</a>
        <a class="button" href="{% url 'jobs' %}">View all your Jobs</a>
        <a class="button" href="{% url 'search_jobs' %}">Search new Jobs</a>
    </div>
  </div>
  
</div>
<br>

<div class="row">
  <div class="large-column">
    <div class="card">
        <h2>Products</h2>
        {% if product_len != 0 %}
        <table id="transactions">
            <tr>
                <th>Name</th>
                <th>Seller</th>
                <th>Price</th>
                <th>Items Left</th>
                <th>Info</th>
                <th>Edit</th>
            </tr>
            {% for product in products %}
            <tr>
                <td>{{ product.name|safe }}</td>
                <td>{{ product.seller.first_name|safe|capfirst }} {{ product.seller.last_name|safe|capfirst }}</td>
                <td>${{ product.price }}</td>
                <td>{{ product.availability }}</td>
                
                <td> <a href="{% url 'view_product' product.id %}">Info</a></td>
                <td> <a href="{% url 'product_edit' product.id %}">Edit</a></td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        No Products
        {% endif %}
        <br>
        <a class="button" href="{% url 'create_product' %}">Create a Product</a>
        <a class="button" href="{% url 'products' %}">View all your Products</a>
        <a class="button" href="{% url 'search_products' %}">View the Shop</a>
    </div>
  </div>
  
</div>

<br>
<br>

<div class="row">
  <div class="large-column">
    <div class="card">
        <h2>Latest Comments</h2>
        {% if comment_len != 0 %}
        <table id="transactions">
            <tr>
                <th>Commenter</th>
                <th>Comment</th>
                <th>Time</th>
                <th>Job</th>
                <th>Info</th>
            </tr>
            {% for comment, Job in comments.items %}
            <tr>
                <td>{{ comment.commenter.first_name|safe|capfirst }} {{ comment.commenter.last_name|safe|capfirst }}</td>
                <td>{{ comment.comment|safe }}</td>
                <td>{{ comment.time }}</td>
                
                <td>{{ Job.name }}</td>
                <td> <a href="{% url 'view_job' Job.id %}">Info</a></td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        No Comments
        {% endif %}
    </div>
  </div>
  
</div>

<br>
<br>

<div class="row">
  <div class="large-column">
    <div class="card">
        <h2>Latest Reviews</h2>
        {% if review_len != 0 %}
        <table id="transactions">
            <tr>
                <th>Reviewer</th>
                <th>Review</th>
                <th>Stars</th>
                <th>Product</th>
                <th>Info</th>
            </tr>
            {% for review, Product in reviews.items %}
            <tr>
                <td>{{ review.commenter.first_name|safe|capfirst }} {{ review.commenter.last_name|safe|capfirst }}</td>
                <td>{{ review.comment|safe }}</td>
                <td>{{ review.stars }}</td>
                
                <td>{{ Product.name }}</td>
                <td> <a href="{% url 'view_product' Product.id %}">Info</a></td>
            </tr>
            {% endfor %}
        </table>
        {% else %}
        No Reviews
        {% endif %}
    </div>
  </div>
  
</div>

<br>
<br>

<script>
  {% if notification %}
    alert('{{ notification }}')
  {% endif %}
</script>
{% endblock %}

templates/job.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block title %}
Job
{% endblock title %}



{% block content %}
    <h1>Job</h1>

    <h2>Name: {{job.name}}</h2>
    <h3>Employer: {{ job.employer.first_name|safe|capfirst }} {{ job.employer.last_name|safe|capfirst }}</h3>
    <h3>Workers: {% for person in job.workers.all %}
        <p class='card-text'>{{ person.first_name|safe|capfirst }} {{ person.last_name|safe|capfirst }}</p>
      {% empty %}
        <p class='card-text'>No Workers</p>
      {% endfor %}</h3>
    <h3>Pay ${{ job.pay }}</h3>
    <h3>Minutes {{ job.minutes }}</h3>
    <h3>Availability {{ job.get_availability_display }}</h3>
    <h3>Description: {{ job.description|safe }} </h3>

    {% for comment in job.comments.all %}
      <br>
      <p>Author {{ comment.commenter.first_name|safe|capfirst }} {{ comment.commenter.last_name|safe|capfirst }}</p>
      <p>{{ comment.comment|safe }}</p>
      <p>Posted on {{ comment.time }}</p>
    {% empty %}
    No Comments
    {% endfor %}
    <br>
    Write a comment
    <form action="" method="post"><input type='hidden'/>
      {%csrf_token %}

      {% for field in form.visible_fields %}
  <div class="form-group">
    {{ field.label_tag }}

    {% if form.is_bound %}
      {% if field.errors %}
        {% render_field field class="form-control is-invalid" %}
        {% for error in field.errors %}
          <div class="invalid-feedback" style="color: rgb(235, 0, 0); font-size: smaller;">
            {{ error }}
          </div>
        {% endfor %}
      {% else %}
        {% render_field field class="form-control is-valid" %}
      {% endif %}
    {% else %}
      {% render_field field class="form-control" %}
    {% endif %}

    {% if field.help_text %}
      <small class="form-text text-muted">{{ field.help_text }}</small>
    {% endif %}
  </div>
{% endfor %}

    <div class="form-group">
      <button type="submit" class="btn btn-default ">
        Post
      </button>

        </div>

      </form>
    <br>
    <br>
    <a class="button" href="{% url 'join_job' job.id %}">Join</a>
    <a class="button" href="{% url 'leave_job' job.id %}">Leave</a>
    <a class="button" href="{% url 'pay_job' job.id %}">Pay Workers</a>
{% endblock content %}

templates/jobs.html
{% extends 'base.html' %}

{% block title %}
Jobs
{% endblock title %}

{% block content %}
{% if job_len != 0 %}
<table id="transactions">
    <tr>
        <th>Name</th>
        <th>Employer</th>
        <th>Description</th>
        <th>Pay</th>
        <th>Minutes</th>
        <th>Availibility</th>
        <th>Workers</th>
        <th>Info</th>
        <th>Edit</th>
    </tr>
    {% for job in jobs %}
    <tr>
        <td>{{ job.name|safe }}</td>
        <td>{{ job.employer.first_name|safe|capfirst }} {{ job.employer.last_name|safe|capfirst }}</td>
        <td>{{ job.description|safe }}</td>
        <td>${{ job.pay }}</td>
        <td>{{ job.minutes }}</td>
        <td>{{ job.get_availability_display }}</td>
        <td>
        {% for person in job.workers.all %}
            <p>{{ person.first_name|safe|capfirst }} {{ person.last_name|safe|capfirst }}</p>
        {% empty %}
            <p class='card-text'>No Workers</p>
        {% endfor %}
</td>
        <td> <a href="{% url 'view_job' job.id %}">Info</a></td>
        <td> <a href="{% url 'job_edit' job.id %}">Edit</a></td>
    </tr>
    {% endfor %}
</table>
{% else %}
No Jobs
<br>
<br>
{% endif %}
<br>
<a class="button" href="{% url 'create_job' %}">Create a Job</a>
<a class="button" href="{% url 'search_jobs' %}">Search new Jobs</a>

{% endblock %}

templates/pay_workers.html
{% extends 'base.html' %}
{% block title %}
Confirm
{% endblock title %}
{% block content %}
  <h2>Are you Sure You want to pay workers?</h2>
  <br>
  {{ text }}
  <p>Bank Stimulus {{ stimulus }}</p>
  <p>You pay {{ price }} plus any bonuses</p>
  <br>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Pay Workers</button>
  </form>

<p>For Custom bonuses please pay separately</p>

<a class="button" href="{% url 'runTransaction' %}">Create a Transaction</a>
<br>
<br>
<script>
    {% if notification %}
    alert('{{ notification }}')
    {% endif %}
    </script>
<br>
<br>
<br>
<br>
{% endblock %}

templates/transaction.html
{% extends 'base.html' %}

{% block title %}
Transaction
{% endblock title %}



{% block content %}
    <h1>Transaction</h1>

    <h3>Sender {{ transaction.payer.first_name|safe|capfirst }} {{ transaction.payer.last_name|safe|capfirst }}</h3>
    <h3>Receiver {{ transaction.receiver.first_name|safe|capfirst }} {{ transaction.receiver.last_name|safe|capfirst }}</h3>
    <h3>Amount ${{ transaction.amount }}</h3>
    <h3>Description: {{ transaction.description|safe }} </h3>
    <h3>Time: {{ time }} </h3>
    <h3>Read: {{ transaction.get_read_display }} </h3>
{% endblock content %}

templates/transactions.html
{% extends 'base.html' %}
{% block title %}
Home
{% endblock title %}

{% block style %}
<style>
* {
  box-sizing: border-box;
}

/* Float four columns side by side */
.small-column {
  float: left;
  width: 23%;
  padding: 0 10px;
}

.big-column {
  float: left;
  width: 50%;
  padding: 0 10px;
}

/* Remove extra left and right margins, due to padding */
.row {margin: 0 -5px;}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive columns */
@media screen and (max-width: 600px) {
  .column {
    width: 100%;
    display: block;
    margin-bottom: 20px;
  }
}

/* Style the counter cards */
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  padding: 16px;
  text-align: center;
  background-color: #f1f1f1;
}

.button {
  background-color: white;
  color: black;
  padding: 5px;
  border: 2px solid #555555;
}

#transactions {
  font-family: Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#transactions td, #transactions th {
  border: 1px solid #ddd;
  padding: 8px;
}

#transactions tr:nth-child(even){background-color: #f2f2f2;}

#transactions tr:hover {background-color: #ddd;}

#transactions th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #04AA6D;
  color: white;
}

</style>
{% endblock %}

{% block content %}
<br>
<h1>Transactions</h1>
{% if len != 0 %}
<table id="transactions">
    <tr>
        <th>Sender</th>
        <th>Receiver</th>
        <th>Amount</th>
        <th>Description</th>
        <th>Time</th>
        <th>Read</th>
        <th>Info</th>
    </tr>
    {% for transaction in transactions %}
    <tr>
        <td>{{ transaction.payer.first_name|safe|capfirst }} {{ transaction.payer.last_name|safe|capfirst }}</td>
        <td>{{ transaction.receiver.first_name|safe|capfirst }} {{ transaction.receiver.last_name|safe|capfirst }}</td>
        <td>${{ transaction.amount }}</td>
        <td> {{ transaction.description|safe }} </td>
        <td>{{ transaction.time }}</td>
        <td> {{ transaction.get_read_display }} </td>
        <td> <a href="{% url 'transaction' transaction.id %}">Info</a></td>
    </tr>
    {% endfor %}
</table>
{% else %}
No Transactions
{% endif %}


{% endblock %}